dane <- read.csv2("data.csv",dec=",")
sep <- by(dane,dane$I,print)

pdf("T35-uh-uc.pdf")
z <- as.data.frame(sep$`3.5`)
plot(z$UH ~ z$UC,xlab="UC[mV]",ylab="UH[mV]",main="UH(UC) B=0,42T")
l <- lm(z$UH ~ z$UC)
abline(l)
summary(l)
dev.off()

pdf("T30-uh-uc.pdf")
z <- as.data.frame(sep$`3`)
plot(z$UH ~ z$UC,xlab="UC[mV]",ylab="UH[mV]",main="UH(UC) B=0,41T")
l <- lm(z$UH ~ z$UC)
abline(l)
summary(l)
dev.off()

pdf("T25-uh-uc.pdf")
z <- as.data.frame(sep$`2.5`)
plot(z$UH ~ z$UC,xlab="UC[mV]",ylab="UH[mV]",main="UH(UC) B=0,39T")
l <- lm(z$UH ~ z$UC)
abline(l)
summary(l)
dev.off()

pdf("T20-uh-uc.pdf")
z <- as.data.frame(sep$`2`)
plot(z$UH ~ z$UC,xlab="UC[mV]",ylab="UH[mV]",main="UH(UC) B=-0,36T")
l <- lm(z$UH ~ z$UC)
abline(l)
summary(l)
dev.off()

pdf("T15-uh-uc.pdf")
z <- as.data.frame(sep$`1.5`)
plot(z$UH ~ z$UC,,xlab="UC[mV]",ylab="UH[mV]",main="UH(UC) B=0,32T")
l <- lm(z$UH ~ z$UC)
abline(l)
summary(l)
dev.off()

pdf("T10-uh-uc.pdf")
z <- as.data.frame(sep$`1`)
plot(z$UH ~ z$UC,xlab="UC[mV]",ylab="UH[mV]",main="UH(UC) B=0,26T")
l <- lm(z$UH ~ z$UC)
abline(l)
summary(l)
dev.off()

pdf("T05-uh-uc.pdf")
z <- as.data.frame(sep$`0.5`)
plot(z$UH ~ z$UC,xlab="UC[mV]",ylab="UH[mV]",main="UH(UC) B=0,12T")
l <- lm(z$UH ~ z$UC)
abline(l)
summary(l)
dev.off()

pdf("T-05-uh-uc.pdf")
z <- as.data.frame(sep$`-0.5`)
plot(z$UH ~ z$UC,xlab="UC[mV]",ylab="UH[mV]",main="UH(UC) B=-0,12T")
l <- lm(z$UH ~ z$UC)
abline(l)
summary(l)
dev.off()

pdf("T-10-uh-uc.pdf")
z <- as.data.frame(sep$`-1`)
plot(z$UH ~ z$UC,xlab="UC[mV]",ylab="UH[mV]",main="UH(UC) B=-0,26T")
l <- lm(z$UH ~ z$UC)
abline(l)
summary(l)
dev.off()

pdf("T-15-uh-uc.pdf")
z <- as.data.frame(sep$`-1.5`)
plot(z$UH ~ z$UC,xlab="UC[mV]",ylab="UH[mV]",main="UH(UC) B=-0,32T")
l <- lm(z$UH ~ z$UC)
abline(l)
summary(l)
dev.off()

pdf("T-20-uh-uc.pdf")
z <- as.data.frame(sep$`-2`)
plot(z$UH ~ z$UC,xlab="UC[mV]",ylab="UH[mV]",main="UH(UC) B=-0,36T")
l <- lm(z$UH ~ z$UC)
abline(l)
summary(l)
dev.off()

pdf("T-25-uh-uc.pdf")
z <- as.data.frame(sep$`-2.5`)
plot(z$UH ~ z$UC,xlab="UC[mV]",ylab="UH[mV]",main="UH(UC) B=-0,39T")
l <- lm(z$UH ~ z$UC)
abline(l)
summary(l)
dev.off()

pdf("T-30-uh-uc.pdf")
z <- as.data.frame(sep$`-3`)
plot(z$UH ~ z$UC,xlab="UC[mV]",ylab="UH[mV]",main="UH(UC) B=-0,41T")
l <- lm(z$UH ~ z$UC)
abline(l)
summary(l)
dev.off()

pdf("T-35-uh-uc.pdf")
z <- as.data.frame(sep$`-3.5`)
plot(z$UH ~ z$UC,xlab="UC[mV]",ylab="UH[mV]",main="UH(UC) B=-0,42T")
l <- lm(z$UH ~ z$UC)
abline(l)
summary(l)
dev.off()


#Nowe tutaj...


pdf("T35-uh-ur.pdf")
z <- as.data.frame(sep$`3.5`)
plot(z$UH ~ z$UR,xlab="UR[V]",ylab="UH[mV]",main="UH(UR) B=0,42T")
l <- lm(z$UH ~ z$UR)
abline(l)
summary(l)
dev.off()

pdf("T30-uh-ur.pdf")
z <- as.data.frame(sep$`3`)
plot(z$UH ~ z$UR,xlab="UR[V]",ylab="UH[mV]",main="UH(UR) B=0,41T")
l <- lm(z$UH ~ z$UR)
abline(l)
summary(l)
dev.off()

pdf("T25-uh-ur.pdf")
z <- as.data.frame(sep$`2.5`)
plot(z$UH ~ z$UR,xlab="UR[V]",ylab="UH[mV]",main="UH(UR) B=0,39T")
l <- lm(z$UH ~ z$UR)
abline(l)
summary(l)
dev.off()

pdf("T20-uh-ur.pdf")
z <- as.data.frame(sep$`2`)
plot(z$UH ~ z$UR,xlab="UR[V]",ylab="UH[mV]",main="UH(UR) B=-0,36T")
l <- lm(z$UH ~ z$UR)
abline(l)
summary(l)
dev.off()

pdf("T15-uh-ur.pdf")
z <- as.data.frame(sep$`1.5`)
plot(z$UH ~ z$UR,,xlab="UR[V]",ylab="UH[mV]",main="UH(UR) B=0,32T")
l <- lm(z$UH ~ z$UR)
abline(l)
summary(l)
dev.off()

pdf("T10-uh-ur.pdf")
z <- as.data.frame(sep$`1`)
plot(z$UH ~ z$UR,xlab="UR[V]",ylab="UH[mV]",main="UH(UR) B=0,26T")
l <- lm(z$UH ~ z$UR)
abline(l)
summary(l)
dev.off()

pdf("T05-uh-ur.pdf")
z <- as.data.frame(sep$`0.5`)
plot(z$UH ~ z$UR,xlab="UR[V]",ylab="UH[mV]",main="UH(UR) B=0,12T")
l <- lm(z$UH ~ z$UR)
abline(l)
summary(l)
dev.off()

pdf("T-05-uh-ur.pdf")
z <- as.data.frame(sep$`-0.5`)
plot(z$UH ~ z$UR,xlab="UR[V]",ylab="UH[mV]",main="UH(UR) B=-0,12T")
l <- lm(z$UH ~ z$UR)
abline(l)
summary(l)
dev.off()

pdf("T-10-uh-ur.pdf")
z <- as.data.frame(sep$`-1`)
plot(z$UH ~ z$UR,xlab="UR[V]",ylab="UH[mV]",main="UH(UR) B=-0,26T")
l <- lm(z$UH ~ z$UR)
abline(l)
summary(l)
dev.off()

pdf("T-15-uh-ur.pdf")
z <- as.data.frame(sep$`-1.5`)
plot(z$UH ~ z$UR,xlab="UR[V]",ylab="UH[mV]",main="UH(UR) B=-0,32T")
l <- lm(z$UH ~ z$UR)
abline(l)
summary(l)
dev.off()

pdf("T-20-uh-ur.pdf")
z <- as.data.frame(sep$`-2`)
plot(z$UH ~ z$UR,xlab="UR[V]",ylab="UH[mV]",main="UH(UR) B=-0,36T")
l <- lm(z$UH ~ z$UR)
abline(l)
summary(l)
dev.off()

pdf("T-25-uh-ur.pdf")
z <- as.data.frame(sep$`-2.5`)
plot(z$UH ~ z$UR,xlab="UR[V]",ylab="UH[mV]",main="UH(UR) B=-0,39T")
l <- lm(z$UH ~ z$UR)
abline(l)
summary(l)
dev.off()

pdf("T-30-uh-ur.pdf")
z <- as.data.frame(sep$`-3`)
plot(z$UH ~ z$UR,xlab="UR[V]",ylab="UH[mV]",main="UH(UR) B=-0,41T")
l <- lm(z$UH ~ z$UR)
abline(l)
summary(l)
dev.off()

pdf("T-35-uh-ur.pdf")
z <- as.data.frame(sep$`-3.5`)
plot(z$UH ~ z$UR,xlab="UR[V]",ylab="UH[mV]",main="UH(UR) B=-0,42T")
l <- lm(z$UH ~ z$UR)
abline(l)
summary(l)
dev.off()

pdf("T-35-uh-ur.pdf")
z <- as.data.frame(sep$`-3.5`)
plot(z$UH ~ z$UR,xlab="UR[V]",ylab="UH[mV]",main="UH(UR) B=-0,42T")
l <- lm(z$UH ~ z$UR)
abline(l)
summary(l)
dev.off()

#Ostatnie

pdf("uc-ur.pdf")
z <- as.data.frame(sep$`-3.5`)
plot(z$UR ~ z$UC,xlab="UC[mV]",ylab="UR[V]",main="UR(UC)")
l <- lm(z$UR ~ z$UC)
abline(l)
summary(l)
dev.off()
