dane <- read.csv2("data.csv",dec=",")
sep <- by(dane,dane$I,print)

png("T35-uh-uc.png")
z <- as.data.frame(sep$`3.5`)
plot(z$UH ~ z$UC,xlab="UC[mV]",ylab="UH[mV]",main="UH(UC) B=0,42T")
l <- lm(z$UH ~ z$UC)
abline(l)
summary(l)
dev.off()

png("T30-uh-uc.png")
z <- as.data.frame(sep$`3`)
plot(z$UH ~ z$UC,xlab="UC[mV]",ylab="UH[mV]",main="UH(UC) B=0,41T")
l <- lm(z$UH ~ z$UC)
abline(l)
summary(l)
dev.off()

png("T25-uh-uc.png")
z <- as.data.frame(sep$`2.5`)
plot(z$UH ~ z$UC,xlab="UC[mV]",ylab="UH[mV]",main="UH(UC) B=0,39T")
l <- lm(z$UH ~ z$UC)
abline(l)
summary(l)
dev.off()

png("T20-uh-uc.png")
z <- as.data.frame(sep$`2`)
plot(z$UH ~ z$UC,xlab="UC[mV]",ylab="UH[mV]",main="UH(UC) B=-0,36T")
l <- lm(z$UH ~ z$UC)
abline(l)
summary(l)
dev.off()

png("T15-uh-uc.png")
z <- as.data.frame(sep$`1.5`)
plot(z$UH ~ z$UC,,xlab="UC[mV]",ylab="UH[mV]",main="UH(UC) B=0,32T")
l <- lm(z$UH ~ z$UC)
abline(l)
summary(l)
dev.off()

png("T10-uh-uc.png")
z <- as.data.frame(sep$`1`)
plot(z$UH ~ z$UC,xlab="UC[mV]",ylab="UH[mV]",main="UH(UC) B=0,26T")
l <- lm(z$UH ~ z$UC)
abline(l)
summary(l)
dev.off()

png("T5-uh-uc.png")
z <- as.data.frame(sep$`0.5`)
plot(z$UH ~ z$UC,xlab="UC[mV]",ylab="UH[mV]",main="UH(UC) B=0,12T")
l <- lm(z$UH ~ z$UC)
abline(l)
summary(l)
dev.off()

png("T-05-uh-uc.png")
z <- as.data.frame(sep$`-0.5`)
plot(z$UH ~ z$UC,xlab="UC[mV]",ylab="UH[mV]",main="UH(UC) B=-0,12T")
l <- lm(z$UH ~ z$UC)
abline(l)
summary(l)
dev.off()

png("T-10-uh-uc.png")
z <- as.data.frame(sep$`-1`)
plot(z$UH ~ z$UC,xlab="UC[mV]",ylab="UH[mV]",main="UH(UC) B=-0,26T")
l <- lm(z$UH ~ z$UC)
abline(l)
summary(l)
dev.off()

png("T-15-uh-uc.png")
z <- as.data.frame(sep$`-1.5`)
plot(z$UH ~ z$UC,xlab="UC[mV]",ylab="UH[mV]",main="UH(UC) B=-0,32T")
l <- lm(z$UH ~ z$UC)
abline(l)
summary(l)
dev.off()

png("T-20-uh-uc.png")
z <- as.data.frame(sep$`-2`)
plot(z$UH ~ z$UC,xlab="UC[mV]",ylab="UH[mV]",main="UH(UC) B=-0,36T")
l <- lm(z$UH ~ z$UC)
abline(l)
summary(l)
dev.off()

png("T-25-uh-uc.png")
z <- as.data.frame(sep$`-2.5`)
plot(z$UH ~ z$UC,xlab="UC[mV]",ylab="UH[mV]",main="UH(UC) B=-0,39T")
l <- lm(z$UH ~ z$UC)
abline(l)
summary(l)
dev.off()

png("T-30-uh-uc.png")
z <- as.data.frame(sep$`-3`)
plot(z$UH ~ z$UC,xlab="UC[mV]",ylab="UH[mV]",main="UH(UC) B=-0,41T")
l <- lm(z$UH ~ z$UC)
abline(l)
summary(l)
dev.off()

png("T-35-uh-uc.png")
z <- as.data.frame(sep$`-3.5`)
plot(z$UH ~ z$UC,xlab="UC[mV]",ylab="UH[mV]",main="UH(UC) B=-0,42T")
l <- lm(z$UH ~ z$UC)
abline(l)
summary(l)
dev.off()